database:
  url: "jdbc:mysql://mudb.learn.mulesoft.com:3306/training?user=mule&password=mule"
  driverclass: "com.mysql.cj.jdbc.Driver"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"

file:
  accountsDir: "/Users/wenyuejun/AnypointStudio/studio-workspace/Diy_8-1_ForEach_Watermarking"
  
accounts:
  folder:
    out: "output"
  filename:
      prefix: "customer-accounts"
      ext: ".csv"